### ISSUE TITLE
Getting PineconeArgumentError from examples

### ISSUE THREAD

**Issue by mk0y** [run-llama/LlamaIndexTS#362]
Hi,
I'm using Pinecode vector store, and trying to learn from your examples.
I successfully inserted data in the store using [pinecone-vector-store/load-docs.ts](https://github.com/run-llama/LlamaIndexTS/blob/main/examples/pinecone-vector-store/load-docs.ts).
Next, i run [pinecone-vector-store/query.ts](https://github.com/run-llama/LlamaIndexTS/blob/main/examples/pinecone-vector-store/query.ts) with a custom question, but I'm getting the following error:

```
Error: PineconeArgumentError: The argument to query accepts multiple types. Either 1) must not have property: vector.  Must have required property: id. There were also validation errors: argument must NOT have additional properties, argument must NOT have additional properties. 2) had validation errors: argument must NOT have additional properties, argument must NOT have additional properties.
```

The `query` method has the following definition:

```ts
/**
 * A query engine is a question answerer that can use one or more steps.
 */
interface BaseQueryEngine {
    /**
     * Query the query engine and get a response.
     * @param query
     * @param parentEvent
     */
    query(query: string, parentEvent?: Event): Promise<Response>;
}
```

I don't see why is this error appearing. Any ideas?

**Comment by marcusschiesser** [comment]
@mk0y Thanks for your bug report - Pinecone support was a community contribution by @mtutty - Michael, can you please have a look?

**Comment by Ahmed14z** [comment]
same error here

**Comment by israa-junaid** [comment]
Im also facing the same error

**Comment by israa-junaid** [comment]
@mtutty - Michael can please update us regarding this error?

**Comment by marcusschiesser** [comment]
I just merged https://github.com/run-llama/LlamaIndexTS/pull/507 - can someone please check if it fixes this error?

**Comment by Sandeepsuresh1998** [comment]
Hey @marcusschiesser it unfortunately didn't fix the issue. I'm digging into it a little now but from my first glance, I believe the pinecone sdk isn't receiving the actual embedding from the index properly. Will follow up.

**Comment by marcusschiesser** [comment]
@martimatix I guess your PR (https://github.com/run-llama/LlamaIndexTS/pull/510) solves this issue?

**Comment by martimatix** [comment]
Yup, confirming it fixed the issue.
